name: Deploy Release to AWS EC2

on:
  push:
    tags:
      - "v*.*.*"

  workflow_dispatch:
    inputs:
      version:
        description: "Release tag to deploy (example: v1.1.0)"
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy release to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/recipe-finder

            git fetch --tags origin

            if [ -n "${{ github.event.inputs.version }}" ]; then
              VERSION="${{ github.event.inputs.version }}"
            else
              VERSION="${{ github.ref_name }}"
            fi

            echo "Deploying version: $VERSION"

            git checkout "tags/$VERSION" --detach

            git log -1 --oneline

            docker compose build
            docker compose up -d
            docker compose ps
